/**
 * Do not edit directly
 * Generated on Mon, 25 Jul 2022 05:23:59 GMT
 */

export const tokens = {
primary25: '#fdf9f8',
primary50: '#fcf3f1',
primary100: '#fae7e4',
primary200: '#f6cdc5',
primary300: '#f1afa1',
primary400: '#ec8b72',
primary500: '#e8590c',
primary600: '#cf4f0a',
primary700: '#b34409',
primary800: '#923807',
primary900: '#672705',
buttonsLgPaddingLeftRight: '16px',
buttonsLgPaddingTopBottom: '12px',
buttonsLgFontSize: '18px',
buttonsLgTypographyFontFamily: 'Nunito Sans',
buttonsLgTypographyFontWeight: 'Bold',
buttonsLgTypographyLineHeight: '24px',
buttonsLgTypographyFontSize: '16px',
buttonsLgTypographyLetterSpacing: '0px',
buttonsLgTypographyParagraphSpacing: '0px',
buttonsLgTypographyTextCase: 'none',
buttonsLgTypographyTextDecoration: 'none',
buttonsLgIconSize: '20px',
buttonsSmPaddingLeftRight: '12px',
buttonsSmPaddingTopBottom: '8px',
buttonsSmFontSize: '14px',
buttonsSmTypographyFontFamily: 'Nunito Sans',
buttonsSmTypographyFontWeight: 'Bold',
buttonsSmTypographyLineHeight: '18px',
buttonsSmTypographyFontSize: '12px',
buttonsSmTypographyLetterSpacing: '0px',
buttonsSmTypographyParagraphSpacing: '0px',
buttonsSmTypographyTextCase: 'none',
buttonsSmTypographyTextDecoration: 'none',
buttonsSmIconSize: '12px',
buttonsPrimaryDefaultBackgroundColor: '#e8590c',
buttonsPrimaryDefaultColor: '#ffffff',
buttonsPrimaryHoverBackgroundColor: '#cf4f0a',
buttonsPrimaryHoverColor: '#ffffff',
buttonsPrimaryActiveBackgroundColor: '#b34409',
buttonsPrimaryActiveColor: '#ffffff',
buttonsPrimaryFocusBackgroundColors: '#e8590c',
buttonsPrimaryFocusColor: '#ffffff',
buttonsPrimaryFocusBorderColors: '#f1afa1',
buttonsPrimaryDisabledBackgroundColor: '#b1b1b1',
buttonsPrimaryDisabledColor: '#616161',
buttonsPrimaryBorderWidth: '0px',
buttonsSecondaryDefaultBackgroundColor: '#fcf3f1',
buttonsSecondaryDefaultColor: '#e8590c',
buttonsSecondaryHoverBackgroundColor: '#fae7e4',
buttonsSecondaryHoverColor: '#cf4f0a',
buttonsSecondaryActiveBackgroundColor: '#f6cdc5',
buttonsSecondaryActiveColor: '#cf4f0a',
buttonsSecondaryFocusBackgroundColor: '#fcf3f1',
buttonsSecondaryFocusColor: '#e8590c',
buttonsSecondaryFocusBorderColors: '#f1afa1',
buttonsSecondaryDisabledBackgroundColor: '#f3f3f3',
buttonsSecondaryDisabledColor: '#cecece',
buttonsSecondaryBorderWidth: '0px',
buttonsBorderRadius: '8px',
buttonsMdPaddingLeftRight: '12px',
buttonsMdPaddingTopBottom: '8px',
buttonsMdFontSize: '16px',
buttonsMdTypographyFontFamily: 'Nunito Sans',
buttonsMdTypographyFontWeight: 'Bold',
buttonsMdTypographyLineHeight: '20px',
buttonsMdTypographyFontSize: '14px',
buttonsMdTypographyLetterSpacing: '0px',
buttonsMdTypographyParagraphSpacing: '0px',
buttonsMdTypographyTextCase: 'none',
buttonsMdTypographyTextDecoration: 'none',
buttonsMdIconSize: '16px',
checkboxDefaultBackgroundColor: '#ffffff',
checkboxDefaultBorder: '#cecece',
checkboxDisabledBackgroundColor: '#e8e8e8',
checkboxDisabledBorder: '#b1b1b1',
checkboxActiveDisableBackgroundColor: '#f1afa1',
checkboxActiveDisableColor: '#ffffff',
checkboxActiveDisableBorder: '#e8590c',
checkboxActiveBackgroundColor: '#e8590c',
checkboxActiveColor: '#ffffff',
checkboxActiveBorder: '#cf4f0a',
checkboxBorderRadius: '4px',
checkboxBorderWidth: '1px',
checkboxTextEnable: '#3d3d3d',
checkboxTextDisable: '#8f8f8f',
radioBorderWidth: '1px',
radioDefaultBackgroundColor: '#ffffff',
radioDefaultBorder: '#cecece',
radioDisableBackgroundColor: '#e8e8e8',
radioDisableBorder: '#b1b1b1',
radioActiveBackgroundColor: '#ffffff',
radioActiveBorder: '#e8590c',
radioActiveDisableBackgroundColor: '#ffffff',
radioActiveDisableBorder: '#f1afa1',
radioTextEnable: '#3d3d3d',
radioTextDisable: '#8f8f8f',
anchorDefaultColor: '#e8590c',
anchorHoverColor: '#cf4f0a',
anchorActiveColor: '#b34409',
anchorFocusColor: '#e8590c',
anchorFocusBorderColor: '#f1afa1',
anchorDisableColor: '#b1b1b1',
anchorLgFontSize: '18px',
anchorLgIconSize: '20px',
anchorMdFontSize: '16px',
anchorMdIconSize: '16px',
anchorSmFontSize: '14px',
anchorSmIconSize: '12px',
switchActiveBackgroundColor: '#e8590c',
switchActiveDisableBackgroundColor: '#f6cdc5',
switchNonactiveBackgroundColor: '#b1b1b1',
switchNonactiveDisableBackgroundColor: '#e8e8e8',
buttonX: '0px',
buttonY: '0px',
buttonBlur: '0px',
buttonSpread: '0px',
buttonColor: '#000000',
buttonType: 'dropShadow',
avatarLgSize: '64px',
avatarLgIconSize: '40px',
avatarLgFontSize: '18px',
avatarMdSize: '40px',
avatarMdIconSize: '24px',
avatarMdFontSize: '16px',
avatarSmSize: '32px',
avatarSmIconSize: '16px',
avatarSmFontSize: '12px',

}

export default tokens
