/**
 * Do not edit directly
 * Generated on Sun, 24 Jul 2022 15:44:08 GMT
 */

export const tokens = {
primary25: '#f8fafc',
primary50: '#f1f5f9',
primary100: '#e4eaf3',
primary200: '#c5d4e6',
primary300: '#a1bbd9',
primary400: '#729ecb',
primary500: '#007bbc',
primary600: '#006ea8',
primary700: '#005f91',
primary800: '#004d76',
primary900: '#003754',
buttonsLgPaddingLeftRight: '16px',
buttonsLgPaddingTopBottom: '12px',
buttonsLgFontSize: '18px',
buttonsLgTypographyFontFamily: 'Nunito Sans',
buttonsLgTypographyFontWeight: 'Bold',
buttonsLgTypographyLineHeight: '24px',
buttonsLgTypographyFontSize: '16px',
buttonsLgTypographyLetterSpacing: '0px',
buttonsLgTypographyParagraphSpacing: '0px',
buttonsLgTypographyTextCase: 'none',
buttonsLgTypographyTextDecoration: 'none',
buttonsLgIconSize: '20px',
buttonsSmPaddingLeftRight: '12px',
buttonsSmPaddingTopBottom: '8px',
buttonsSmFontSize: '14px',
buttonsSmTypographyFontFamily: 'Nunito Sans',
buttonsSmTypographyFontWeight: 'Bold',
buttonsSmTypographyLineHeight: '18px',
buttonsSmTypographyFontSize: '12px',
buttonsSmTypographyLetterSpacing: '0px',
buttonsSmTypographyParagraphSpacing: '0px',
buttonsSmTypographyTextCase: 'none',
buttonsSmTypographyTextDecoration: 'none',
buttonsSmIconSize: '12px',
buttonsPrimaryDefaultBackgroundColor: '#007bbc',
buttonsPrimaryDefaultColor: '#ffffff',
buttonsPrimaryHoverBackgroundColor: '#006ea8',
buttonsPrimaryHoverColor: '#ffffff',
buttonsPrimaryActiveBackgroundColor: '#005f91',
buttonsPrimaryActiveColor: '#ffffff',
buttonsPrimaryFocusBackgroundColors: '#007bbc',
buttonsPrimaryFocusColor: '#ffffff',
buttonsPrimaryFocusBorderColors: '#a1bbd9',
buttonsPrimaryDisabledBackgroundColor: '#b1b1b1',
buttonsPrimaryDisabledColor: '#616161',
buttonsPrimaryBorderWidth: '0px',
buttonsSecondaryDefaultBackgroundColor: '#f1f5f9',
buttonsSecondaryDefaultColor: '#007bbc',
buttonsSecondaryHoverBackgroundColor: '#e4eaf3',
buttonsSecondaryHoverColor: '#006ea8',
buttonsSecondaryActiveBackgroundColor: '#c5d4e6',
buttonsSecondaryActiveColor: '#006ea8',
buttonsSecondaryFocusBackgroundColor: '#f1f5f9',
buttonsSecondaryFocusColor: '#007bbc',
buttonsSecondaryFocusBorderColors: '#007bbc',
buttonsSecondaryDisabledBackgroundColor: '#f3f3f3',
buttonsSecondaryDisabledColor: '#cecece',
buttonsSecondaryBorderWidth: '0px',
buttonsBorderRadius: '500px',
buttonsMdPaddingLeftRight: '12px',
buttonsMdPaddingTopBottom: '8px',
buttonsMdFontSize: '16px',
buttonsMdTypographyFontFamily: 'Nunito Sans',
buttonsMdTypographyFontWeight: 'Bold',
buttonsMdTypographyLineHeight: '20px',
buttonsMdTypographyFontSize: '14px',
buttonsMdTypographyLetterSpacing: '0px',
buttonsMdTypographyParagraphSpacing: '0px',
buttonsMdTypographyTextCase: 'none',
buttonsMdTypographyTextDecoration: 'none',
buttonsMdIconSize: '16px',
checkboxDefaultBackgroundColor: '#ffffff',
checkboxDefaultBorder: '#cecece',
checkboxDisabledBackgroundColor: '#e8e8e8',
checkboxDisabledBorder: '#b1b1b1',
checkboxActiveDisableBackgroundColor: '#a1bbd9',
checkboxActiveDisableColor: '#ffffff',
checkboxActiveDisableBorder: '#007bbc',
checkboxActiveBackgroundColor: '#007bbc',
checkboxActiveColor: '#ffffff',
checkboxActiveBorder: '#006ea8',
checkboxBorderRadius: '4px',
checkboxBorderWidth: '1px',
checkboxTextEnable: '#36146b',
checkboxTextDisable: '#8f8f8f',
radioBorderWidth: '1px',
radioDefaultBackgroundColor: '#ffffff',
radioDefaultBorder: '#cecece',
radioDisableBackgroundColor: '#e8e8e8',
radioDisableBorder: '#b1b1b1',
radioActiveBackgroundColor: '#ffffff',
radioActiveBorder: '#007bbc',
radioActiveDisableBackgroundColor: '#ffffff',
radioActiveDisableBorder: '#a1bbd9',
radioTextEnable: '#36146b',
radioTextDisable: '#8f8f8f',
anchorDefaultColor: '#007bbc',
anchorHoverColor: '#006ea8',
anchorActiveColor: '#005f91',
anchorFocusColor: '#007bbc',
anchorDisableColor: '#b1b1b1',
anchorLgFontSize: '18px',
anchorLgIconSize: '20px',
anchorMdFontSize: '16px',
anchorMdIconSize: '16px',
anchorSmFontSize: '14px',
anchorSmIconSize: '12px',
switchActiveBackgroundColor: '#007bbc',
switchActiveDisableBackgroundColor: '#c5d4e6',
switchNonactiveBackgroundColor: '#b1b1b1',
switchNonactiveDisableBackgroundColor: '#e8e8e8',
buttonX: '0px',
buttonY: '0px',
buttonBlur: '0px',
buttonSpread: '0px',
buttonColor: '#000000',
buttonType: 'dropShadow',
avatarLgSize: '64px',
avatarLgIconSize: '40px',
avatarLgFontSize: '18px',
avatarMdSize: '40px',
avatarMdIconSize: '24px',
avatarMdFontSize: '16px',
avatarSmSize: '32px',
avatarSmIconSize: '16px',
avatarSmFontSize: '12px',

}

export default tokens
