/**
 * Do not edit directly
 * Generated on Sat, 23 Jul 2022 23:14:06 GMT
 */

export const tokens = {
primary-25: '#f8fafc',
primary-50: '#f1f5f9',
primary-100: '#e4eaf3',
primary-200: '#c5d4e6',
primary-300: '#a1bbd9',
primary-400: '#729ecb',
primary-500: '#007bbc',
primary-600: '#006ea8',
primary-700: '#005f91',
primary-800: '#004d76',
primary-900: '#003754',
buttons-lg-padding-left-right: '16px',
buttons-lg-padding-top-bottom: '12px',
buttons-lg-font-size: '18px',
buttons-lg-typography-font-family: 'Nunito Sans',
buttons-lg-typography-font-weight: 'Bold',
buttons-lg-typography-line-height: '24px',
buttons-lg-typography-font-size: '16px',
buttons-lg-typography-letter-spacing: '0px',
buttons-lg-typography-paragraph-spacing: '0px',
buttons-lg-typography-text-case: 'none',
buttons-lg-typography-text-decoration: 'none',
buttons-lg-icon-size: '20px',
buttons-sm-padding-left-right: '12px',
buttons-sm-padding-top-bottom: '8px',
buttons-sm-font-size: '14px',
buttons-sm-typography-font-family: 'Nunito Sans',
buttons-sm-typography-font-weight: 'Bold',
buttons-sm-typography-line-height: '18px',
buttons-sm-typography-font-size: '12px',
buttons-sm-typography-letter-spacing: '0px',
buttons-sm-typography-paragraph-spacing: '0px',
buttons-sm-typography-text-case: 'none',
buttons-sm-typography-text-decoration: 'none',
buttons-sm-icon-size: '12px',
buttons-primary-default-background-color: '#007bbc',
buttons-primary-default-color: '#ffffff',
buttons-primary-hover-background-color: '#006ea8',
buttons-primary-hover-color: '#ffffff',
buttons-primary-active-background-color: '#005f91',
buttons-primary-active-color: '#ffffff',
buttons-primary-focus-background-colors: '#007bbc',
buttons-primary-focus-color: '#ffffff',
buttons-primary-focus-border-colors: '#a1bbd9',
buttons-primary-disabled-background-color: '#b1b1b1',
buttons-primary-disabled-color: '#616161',
buttons-primary-border-width: '0px',
buttons-secondary-default-background-color: '#f1f5f9',
buttons-secondary-default-color: '#007bbc',
buttons-secondary-hover-background-color: '#e4eaf3',
buttons-secondary-hover-color: '#006ea8',
buttons-secondary-active-background-color: '#c5d4e6',
buttons-secondary-active-color: '#006ea8',
buttons-secondary-focus-background-color: '#f1f5f9',
buttons-secondary-focus-color: '#007bbc',
buttons-secondary-focus-border-colors: '#007bbc',
buttons-secondary-disabled-background-color: '#f3f3f3',
buttons-secondary-disabled-color: '#cecece',
buttons-secondary-border-width: '0px',
buttons-border-radius: '500px',
buttons-md-padding-left-right: '12px',
buttons-md-padding-top-bottom: '8px',
buttons-md-font-size: '16px',
buttons-md-typography-font-family: 'Nunito Sans',
buttons-md-typography-font-weight: 'Bold',
buttons-md-typography-line-height: '20px',
buttons-md-typography-font-size: '14px',
buttons-md-typography-letter-spacing: '0px',
buttons-md-typography-paragraph-spacing: '0px',
buttons-md-typography-text-case: 'none',
buttons-md-typography-text-decoration: 'none',
buttons-md-icon-size: '16px',
checkbox-default-background-color: '#ffffff',
checkbox-default-border: '#cecece',
checkbox-disabled-background-color: '#e8e8e8',
checkbox-disabled-border: '#b1b1b1',
checkbox-active-disable-background-color: '#a1bbd9',
checkbox-active-disable-color: '#ffffff',
checkbox-active-disable-border: '#007bbc',
checkbox-active-background-color: '#007bbc',
checkbox-active-color: '#ffffff',
checkbox-active-border: '#006ea8',
checkbox-border-radius: '4px',
checkbox-border-width: '1px',
checkbox-text-enable: '#36146b',
checkbox-text-disable: '#8f8f8f',
radio-border-width: '1px',
radio-default-background-color: '#ffffff',
radio-default-border: '#cecece',
radio-disable-background-color: '#e8e8e8',
radio-disable-border: '#b1b1b1',
radio-active-background-color: '#ffffff',
radio-active-border: '#007bbc',
radio-active-disable-background-color: '#ffffff',
radio-active-disable-border: '#a1bbd9',
radio-text-enable: '#36146b',
radio-text-disable: '#8f8f8f',
anchor-default-color: '#007bbc',
anchor-hover-color: '#006ea8',
anchor-active-color: '#005f91',
anchor-focus-color: '#007bbc',
anchor-disable-color: '#b1b1b1',
anchor-lg-font-size: '18px',
anchor-lg-icon-size: '20px',
anchor-md-font-size: '16px',
anchor-md-icon-size: '16px',
anchor-sm-font-size: '14px',
anchor-sm-icon-size: '12px',
switch-active-background-color: '#007bbc',
switch-active-disable-background-color: '#c5d4e6',
switch-nonactive-background-color: '#b1b1b1',
switch-nonactive-disable-background-color: '#e8e8e8',
button-x: '0px',
button-y: '0px',
button-blur: '0px',
button-spread: '0px',
button-color: '#000000',
button-type: 'dropShadow',
avatar-lg-size: '64px',
avatar-lg-icon-size: '40px',
avatar-lg-font-size: '18px',
avatar-md-size: '40px',
avatar-md-icon-size: '24px',
avatar-md-font-size: '16px',
avatar-sm-size: '32px',
avatar-sm-icon-size: '16px',
avatar-sm-font-size: '12px',

}

export default tokens
