/**
 * Do not edit directly
 * Generated on Mon, 25 Jul 2022 13:19:16 GMT
 */

export const tokens = {
primary25: '#f8faf8',
primary50: '#f1f5f2',
primary100: '#e4ece5',
primary200: '#c5d7c8',
primary300: '#a1c0a5',
primary400: '#72a67a',
primary500: '#008832',
primary600: '#00792c',
primary700: '#006926',
primary800: '#00561f',
primary900: '#003c16',
buttonsLgPaddingLeftRight: '16px',
buttonsLgPaddingTopBottom: '12px',
buttonsLgFontSize: '18px',
buttonsLgTypographyFontFamily: 'Nunito Sans',
buttonsLgTypographyFontWeight: 'Bold',
buttonsLgTypographyLineHeight: '24px',
buttonsLgTypographyFontSize: '16px',
buttonsLgTypographyLetterSpacing: '0px',
buttonsLgTypographyParagraphSpacing: '0px',
buttonsLgTypographyTextCase: 'none',
buttonsLgTypographyTextDecoration: 'none',
buttonsLgIconSize: '20px',
buttonsSmPaddingLeftRight: '12px',
buttonsSmPaddingTopBottom: '8px',
buttonsSmFontSize: '14px',
buttonsSmTypographyFontFamily: 'Nunito Sans',
buttonsSmTypographyFontWeight: 'Bold',
buttonsSmTypographyLineHeight: '18px',
buttonsSmTypographyFontSize: '12px',
buttonsSmTypographyLetterSpacing: '0px',
buttonsSmTypographyParagraphSpacing: '0px',
buttonsSmTypographyTextCase: 'none',
buttonsSmTypographyTextDecoration: 'none',
buttonsSmIconSize: '12px',
buttonsPrimaryDefaultBackgroundColor: '#008832',
buttonsPrimaryDefaultColor: '#ffffff',
buttonsPrimaryHoverBackgroundColor: '#00792c',
buttonsPrimaryHoverColor: '#ffffff',
buttonsPrimaryActiveBackgroundColor: '#006926',
buttonsPrimaryActiveColor: '#ffffff',
buttonsPrimaryFocusBackgroundColors: '#008832',
buttonsPrimaryFocusColor: '#ffffff',
buttonsPrimaryFocusBorderColors: '#a1c0a5',
buttonsPrimaryDisabledBackgroundColor: '#b1b1b1',
buttonsPrimaryDisabledColor: '#616161',
buttonsPrimaryBorderWidth: '0px',
buttonsSecondaryDefaultBackgroundColor: '#f1f5f2',
buttonsSecondaryDefaultColor: '#008832',
buttonsSecondaryHoverBackgroundColor: '#e4ece5',
buttonsSecondaryHoverColor: '#00792c',
buttonsSecondaryActiveBackgroundColor: '#c5d7c8',
buttonsSecondaryActiveColor: '#00792c',
buttonsSecondaryFocusBackgroundColor: '#f1f5f2',
buttonsSecondaryFocusColor: '#008832',
buttonsSecondaryFocusBorderColors: '#008832',
buttonsSecondaryDisabledBackgroundColor: '#f3f3f3',
buttonsSecondaryDisabledColor: '#cecece',
buttonsSecondaryBorderWidth: '0px',
buttonsBorderRadius: '4px',
buttonsMdPaddingLeftRight: '12px',
buttonsMdPaddingTopBottom: '8px',
buttonsMdFontSize: '16px',
buttonsMdTypographyFontFamily: 'Nunito Sans',
buttonsMdTypographyFontWeight: 'Bold',
buttonsMdTypographyLineHeight: '20px',
buttonsMdTypographyFontSize: '14px',
buttonsMdTypographyLetterSpacing: '0px',
buttonsMdTypographyParagraphSpacing: '0px',
buttonsMdTypographyTextCase: 'none',
buttonsMdTypographyTextDecoration: 'none',
buttonsMdIconSize: '16px',
checkboxDefaultBackgroundColor: '#ffffff',
checkboxDefaultBorder: '#cecece',
checkboxDisabledBackgroundColor: '#e8e8e8',
checkboxDisabledBorder: '#b1b1b1',
checkboxActiveDisableBackgroundColor: '#a1c0a5',
checkboxActiveDisableColor: '#ffffff',
checkboxActiveDisableBorder: '#008832',
checkboxActiveBackgroundColor: '#008832',
checkboxActiveColor: '#ffffff',
checkboxActiveBorder: '#00792c',
checkboxBorderRadius: '4px',
checkboxBorderWidth: '1px',
checkboxTextEnable: '#36146b',
checkboxTextDisable: '#8f8f8f',
radioBorderWidth: '1px',
radioDefaultBackgroundColor: '#ffffff',
radioDefaultBorder: '#cecece',
radioDisableBackgroundColor: '#e8e8e8',
radioDisableBorder: '#b1b1b1',
radioActiveBackgroundColor: '#ffffff',
radioActiveBorder: '#008832',
radioActiveDisableBackgroundColor: '#ffffff',
radioActiveDisableBorder: '#a1c0a5',
radioTextEnable: '#36146b',
radioTextDisable: '#8f8f8f',
anchorDefaultColor: '#008832',
anchorHoverColor: '#00792c',
anchorActiveColor: '#006926',
anchorFocusColor: '#008832',
anchorDisableColor: '#b1b1b1',
anchorLgFontSize: '18px',
anchorLgIconSize: '20px',
anchorMdFontSize: '16px',
anchorMdIconSize: '16px',
anchorSmFontSize: '14px',
anchorSmIconSize: '12px',
switchActiveBackgroundColor: '#008832',
switchActiveDisableBackgroundColor: '#c5d7c8',
switchNonactiveBackgroundColor: '#b1b1b1',
switchNonactiveDisableBackgroundColor: '#e8e8e8',
buttonX: '0px',
buttonY: '0px',
buttonBlur: '0px',
buttonSpread: '0px',
buttonColor: '#000000',
buttonType: 'dropShadow',
avatarLgSize: '64px',
avatarLgIconSize: '40px',
avatarLgFontSize: '18px',
avatarMdSize: '40px',
avatarMdIconSize: '24px',
avatarMdFontSize: '16px',
avatarSmSize: '32px',
avatarSmIconSize: '16px',
avatarSmFontSize: '12px',

}

export default tokens
