/**
 * Do not edit directly
 * Generated on Sat, 23 Jul 2022 23:14:06 GMT
 */

export const tokens = {
primary-25: '#fdf9f8',
primary-50: '#fcf3f1',
primary-100: '#fae7e4',
primary-200: '#f6cdc5',
primary-300: '#f1afa1',
primary-400: '#ec8b72',
primary-500: '#e8590c',
primary-600: '#cf4f0a',
primary-700: '#b34409',
primary-800: '#923807',
primary-900: '#672705',
buttons-lg-padding-left-right: '16px',
buttons-lg-padding-top-bottom: '12px',
buttons-lg-font-size: '18px',
buttons-lg-typography-font-family: 'Nunito Sans',
buttons-lg-typography-font-weight: 'Bold',
buttons-lg-typography-line-height: '24px',
buttons-lg-typography-font-size: '16px',
buttons-lg-typography-letter-spacing: '0px',
buttons-lg-typography-paragraph-spacing: '0px',
buttons-lg-typography-text-case: 'none',
buttons-lg-typography-text-decoration: 'none',
buttons-lg-icon-size: '20px',
buttons-sm-padding-left-right: '12px',
buttons-sm-padding-top-bottom: '8px',
buttons-sm-font-size: '14px',
buttons-sm-typography-font-family: 'Nunito Sans',
buttons-sm-typography-font-weight: 'Bold',
buttons-sm-typography-line-height: '18px',
buttons-sm-typography-font-size: '12px',
buttons-sm-typography-letter-spacing: '0px',
buttons-sm-typography-paragraph-spacing: '0px',
buttons-sm-typography-text-case: 'none',
buttons-sm-typography-text-decoration: 'none',
buttons-sm-icon-size: '12px',
buttons-primary-default-background-color: '#e8590c',
buttons-primary-default-color: '#ffffff',
buttons-primary-hover-background-color: '#cf4f0a',
buttons-primary-hover-color: '#ffffff',
buttons-primary-active-background-color: '#b34409',
buttons-primary-active-color: '#ffffff',
buttons-primary-focus-background-colors: '#e8590c',
buttons-primary-focus-color: '#ffffff',
buttons-primary-focus-border-colors: '#f1afa1',
buttons-primary-disabled-background-color: '#b1b1b1',
buttons-primary-disabled-color: '#616161',
buttons-primary-border-width: '0px',
buttons-secondary-default-background-color: '#fcf3f1',
buttons-secondary-default-color: '#e8590c',
buttons-secondary-hover-background-color: '#fae7e4',
buttons-secondary-hover-color: '#cf4f0a',
buttons-secondary-active-background-color: '#f6cdc5',
buttons-secondary-active-color: '#cf4f0a',
buttons-secondary-focus-background-color: '#fcf3f1',
buttons-secondary-focus-color: '#e8590c',
buttons-secondary-focus-border-colors: '#f1afa1',
buttons-secondary-disabled-background-color: '#f3f3f3',
buttons-secondary-disabled-color: '#cecece',
buttons-secondary-border-width: '0px',
buttons-border-radius: '8px',
buttons-md-padding-left-right: '12px',
buttons-md-padding-top-bottom: '8px',
buttons-md-font-size: '16px',
buttons-md-typography-font-family: 'Nunito Sans',
buttons-md-typography-font-weight: 'Bold',
buttons-md-typography-line-height: '20px',
buttons-md-typography-font-size: '14px',
buttons-md-typography-letter-spacing: '0px',
buttons-md-typography-paragraph-spacing: '0px',
buttons-md-typography-text-case: 'none',
buttons-md-typography-text-decoration: 'none',
buttons-md-icon-size: '16px',
checkbox-default-background-color: '#ffffff',
checkbox-default-border: '#cecece',
checkbox-disabled-background-color: '#e8e8e8',
checkbox-disabled-border: '#b1b1b1',
checkbox-active-disable-background-color: '#f1afa1',
checkbox-active-disable-color: '#ffffff',
checkbox-active-disable-border: '#e8590c',
checkbox-active-background-color: '#e8590c',
checkbox-active-color: '#ffffff',
checkbox-active-border: '#cf4f0a',
checkbox-border-radius: '4px',
checkbox-border-width: '1px',
checkbox-text-enable: '#3d3d3d',
checkbox-text-disable: '#8f8f8f',
radio-border-width: '1px',
radio-default-background-color: '#ffffff',
radio-default-border: '#cecece',
radio-disable-background-color: '#e8e8e8',
radio-disable-border: '#b1b1b1',
radio-active-background-color: '#ffffff',
radio-active-border: '#e8590c',
radio-active-disable-background-color: '#ffffff',
radio-active-disable-border: '#f1afa1',
radio-text-enable: '#3d3d3d',
radio-text-disable: '#8f8f8f',
anchor-default-color: '#e8590c',
anchor-hover-color: '#cf4f0a',
anchor-active-color: '#b34409',
anchor-focus-color: '#e8590c',
anchor-focus-border-color: '#f1afa1',
anchor-disable-color: '#b1b1b1',
anchor-lg-font-size: '18px',
anchor-lg-icon-size: '20px',
anchor-md-font-size: '16px',
anchor-md-icon-size: '16px',
anchor-sm-font-size: '14px',
anchor-sm-icon-size: '12px',
switch-active-background-color: '#e8590c',
switch-active-disable-background-color: '#f6cdc5',
switch-nonactive-background-color: '#b1b1b1',
switch-nonactive-disable-background-color: '#e8e8e8',
button-x: '0px',
button-y: '0px',
button-blur: '0px',
button-spread: '0px',
button-color: '#000000',
button-type: 'dropShadow',
avatar-lg-size: '64px',
avatar-lg-icon-size: '40px',
avatar-lg-font-size: '18px',
avatar-md-size: '40px',
avatar-md-icon-size: '24px',
avatar-md-font-size: '16px',
avatar-sm-size: '32px',
avatar-sm-icon-size: '16px',
avatar-sm-font-size: '12px',

}

export default tokens
